# Generated by Django 2.1.15 on 2021-05-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210521_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='research.Topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='User Type:'),
        ),
    ]
