# Generated by Django 2.1.15 on 2021-05-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210522_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
