# Generated by Django 2.1.15 on 2021-05-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210522_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
