# Generated by Django 3.2 on 2021-05-21 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20210520_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NEW',
            new_name='News',
        ),
    ]
