# Generated by Django 3.2 on 2021-05-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210521_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
