# Generated by Django 2.1.15 on 2021-05-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20210520_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='minidetail',
            new_name='mini_detail',
        ),
    ]
