# Generated by Django 2.1.15 on 2021-05-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchhub',
            old_name='subject',
            new_name='topic',
        ),
    ]
