# Generated by Django 2.1.15 on 2021-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20210519_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='idea',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
