# Generated by Django 2.1.15 on 2021-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20210521_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='file',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='main_image',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
